### ISSUE TITLE
With zoom mode on entire buffer contents deleted

### ISSUE THREAD

**Issue by noctuid** [cyrus-and/zoom#25] opened 2019-07-20 15:12 UTC
A while ago, I started having issues with zoom where it would stop working and my entire buffer contents would be deleted (very annoying when used in combination with undo-tree where the history is corrupted and then I have to go in and restore the file from a backup, but I haven't been using undo tree for a while). Afterwards, I have to disable zoom mode for anything to work right. I've mostly stopped using zoom because I couldn't easily debug this (it's hard to quickly replicate and I haven't been able to get it to show up when edebugging `balance-windows-2`), but maybe someone else has encountered this? I can try to look into this further at some point when I have time. I'm sure this is probably related to interaction with some other package or configuration.

Here's an example backtrace:
```
Debugger entered--Lisp error: (wrong-type-argument number-or-marker-p nil)
  balance-windows-2(#<window 80> t)
  balance-windows-1(#<window 80> t)
  balance-windows()
  zoom--update()
  zoom--handler(#<window 10 on log.org>)
  apply(zoom--handler #<window 10 on log.org>)
  select-window(#<window 10 on log.org>)
  windmove-do-window-select(left nil)
  windmove-left(nil)
  funcall-interactively(windmove-left nil)
  call-interactively(windmove-left nil nil)
  command-execute(windmove-left)
```

**Comment by cyrus-and** [comment] 2019-07-20 16:13
Wow, that's serious, I'm sorry to hear that. I use zoom in my everyday workflow and I've never encountered something like that.

But I can't see how any crash caused by Zoom could corrupt a buffer, moreover since the stacktrace points to `balance-windows-2` maybe this is a bug in Emacs. What version are you using?

If you manage to provide a way for me to attempt to reproduce this I'll be happy to look into it.

**Comment by noctuid** [comment] 2019-07-20 18:54
I'm using emacs 27 right now (master) but have been having this issue as a while. I'm guessing it would happen if I manually called `balance-windows` in the right situation, but I haven't been able to replicate it without zoom. I haven't noticed any clear pattern for when it breaks (usually it doesn't happen until I've had emacs open for a while). I'll let you know if I can get a reproducible example.

**Comment by noctuid** [comment] 2019-07-29 02:02
I found that cause of the deletion of buffer contents is the error occuring during a specific command. Though I don't understand why the deletion happens, it's not directly caused by the error it seems.

I need to double check, but it looks like `balance-windows` is calling `balance-windows-1` with a window that's not actually being displayed in the current frame, which I'm guessing is the cause of the issue. It's hard to debug, because the errors stop at some point, and `balance-windows` starts just doing nothing.

You can close this if you want since it's probably not an issue with zoom, but I may have some questions at some point.

**Comment by cyrus-and** [comment] 2019-07-29 10:34
I'm closing this as there's nothing I can do about it, I tried to to manually trigger what you think is the culprit behavior with no luck (I'm not using Emacs 27 though). But feel free to comment and add other information.

In the meantime I'll give Emacs 27 a try for a while.

Thanks for your patience.

**Closed by cyrus-and** 2019-07-29 10:34 UTC
