### ISSUE TITLE
Not work well with minimap. (because it always balance-window whatever if ignore it)

### ISSUE THREAD

**Issue by zw963** [cyrus-and/zoom#38] opened 2021-12-26 14:16 UTC
https://github.com/dengste/minimap/blob/master/minimap.el

it should be like this:

![image](https://user-images.githubusercontent.com/549126/147410829-f741fa8d-9db7-46fb-9f12-60a6c72e573c.png)

(balance-window) broken this feature.

**Comment by cyrus-and** [comment] 2021-12-26 14:32
It's not super clear from your screenshot what's happening there... Can you help me to reproduce this? What happens if you run `balance-windows` in that case even with `zoom-mode` disabled?

It seems to work fairly well here:

![image](https://user-images.githubusercontent.com/1660263/147411059-11dc7e3f-e028-49fb-acb8-ace82e47b80a.png)

> (balance-window) broken this feature.

Anyway, I cannot get rid of `balance-windows`, and ignored windows are not zoomed yet are subject to balancing. So windows that plan to have a fixed size should enforce that. Now `minimap` seems to work here, yet it appears to be buggy, but for example, [`imenu-list`](https://github.com/bmag/imenu-list) works fine.

**Comment by zw963** [comment] 2021-12-26 16:13
Hi, following is my config

```el
(require 'zoom)

;; (custom-set-variables
;;  '(zoom-size '(0.618 . 0.618)))

(defun size-callback ()
  (cond ((> (frame-pixel-width) 1280) '(90 . 0.75))
        (t                            '(0.5 . 0.5))))

(global-set-key (kbd "C-x +") 'zoom)


(custom-set-variables
 '(zoom-size 'size-callback)
 '(zoom-ignored-major-modes '(dired-mode markdown-mode))
 '(zoom-ignored-buffer-names '(" *MINIMAP*"))
 )

(zoom-mode)

(provide 'zoom_init)

;;; zoom_init.el ends here
```

I am current ignore [this](https://github.com/cyrus-and/zoom/blob/master/zoom.el#L215) line for minimap work correct.
if i am not do like this, will cause minimap expanded like this:

![image](https://user-images.githubusercontent.com/549126/147413841-cf5f6af4-2ff6-4440-af9b-e16309c3e6b5.png)

sorry i am not capture a screenshot on a external monitor, at that case, minimap get expanded will occupy all most half of my frame window.

**Comment by zw963** [comment] 2021-12-26 16:14
BTW: you can try this minimap config. (basically, i move minimap to right, as VS code)

```rb
(require 'minimap)

(setq minimap-window-location 'right)
(setq minimap-width-fraction 0.05)

(global-set-key [(f10)] 'minimap-mode)

(defun initialize-minimap-delay (&optional frame)
  "run minimap mode"
  (when (display-graphic-p)
    (run-with-idle-timer 0 nil 'minimap-mode)))

(if (and (fboundp 'daemonp) (daemonp))
    (add-hook 'find-file-hook 'initialize-minimap-delay t)
  )

(provide 'minimap_init)

;;; minimap_init.el ends here
```

**Comment by cyrus-and** [comment] 2021-12-26 16:49
Oh OK, I apologise, now I recall. So, yeah `imenu-list` works because I added the fix in my init file, see [this](https://github.com/cyrus-and/zoom#why-windows-are-resized-even-when-they-are-ignored) FAQ and #17.

So basically you can do the same for `minimap`:

```el
(defun my/fix-minimap-size ()
  (with-selected-window (get-buffer-window " *MINIMAP*")
    (setq window-size-fixed t)
    (let ((width 10))
      (window-resize (selected-window) (- width (window-total-width)) t t))))

(add-hook 'minimap-mode-hook 'my/fix-minimap-size)
```

Hope it helps.

**Comment by zw963** [comment] 2021-12-26 17:19
Okay, will try tomorrow on my external monitor.

**Comment by zw963** [comment] 2021-12-26 17:30
so, for treemacs, i should do it like this, right?

correct output:

![image](https://user-images.githubusercontent.com/549126/147415694-99a168ee-407e-47a1-87e5-59d2e3e173a2.png)

but current output:

![image](https://user-images.githubusercontent.com/549126/147415713-9d26fcf7-98d2-4bfd-8da8-d7a05835ee4c.png)

**Comment by cyrus-and** [comment] 2021-12-26 18:49
`treemacs` appears to work out-of-the-box here.

Please try to use this `.emacs` when trying to reproduce these issues, so we can start from a common baseline:

```el
(setq custom-file "/dev/null")

(package-initialize)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))

(package-install 'zoom)
(package-install 'treemacs)

(custom-set-variables
 '(zoom-mode t))
```

I usually place it in a separate directory like `/tmp/emacs/.emacs` then I start Emacs with `HOME=/tmp/emacs/ emacs`.

**Comment by zw963** [comment] 2021-12-27 16:08
> `treemacs` appears to work out-of-the-box here.
> 
> Please try to use this `.emacs` when trying to reproduce these issues, so we can start from a common baseline:
> 
> ```emacs-lisp
> (setq custom-file "/dev/null")
> 
> (package-initialize)
> (add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))
> 
> (package-install 'zoom)
> (package-install 'treemacs)
> 
> (custom-set-variables
>  '(zoom-mode t))
> ```
> 
> I usually place it in a separate directory like `/tmp/emacs/.emacs` then I start Emacs with `HOME=/tmp/emacs/ emacs`.

Yes, i know treemacs works as expect, but, i use emacs-lsp, as you can see in the screenshot, which come from https://github.com/emacs-lsp/lsp-dart, it use `lsp-treemacs` package, it not work correct.

I can reproduce use following config following your guide:

```cl
(setq custom-file "/dev/null")

(package-initialize)
(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/"))

(package-install 'zoom)
(package-install 'lsp-dart)

(custom-set-variables
 '(zoom-mode t))
```

Then, open a new file, named `1.dart`, then run `lsp-treemacs-symbols`.

thanks.

BTW: are you try zoom with `helm`? it seem like not work well my helm config too.

```cl
(setq-default helm-display-buffer-default-height (* (frame-height) 0.618))
```

**Comment by cyrus-and** [comment] 2021-12-27 22:59
Look, the fix is always to set `window-size-fixed` to `t` for the windows you don't want to be zoomed. And this is something that the original package authors should do, regardless Zoom, when the decide the size IMHO.

All you have to do is to find an hook, set up an [advice](https://www.gnu.org/software/emacs/manual/html_node/elisp/Advising-Functions.html), or create a utility function, etc. where you do the following for the right window:

```el
(setq window-size-fixed t)
```

I cannot fix all your packages, especially if you don't try first yourself to come up with a solution.

**Comment by cyrus-and** [comment] 2021-12-30 16:43
For `lsp-treemacs`, this seems a good staring point:

```el
(defun fix (&rest _)
  (with-selected-window (get-buffer-window "*LSP Symbols List*")
    (setq window-size-fixed t)
    (let ((width 30))
      (window-resize (selected-window) (- width (window-total-width)) t t))))

(advice-add 'lsp-treemacs-render :after 'fix)
```

**Comment by zw963** [comment] 2021-12-30 17:18
Hi, i am not zoom package for now because several issue with helm/lsp-treemacs, in fact, above solutiot work, because
buffer name hcan be change i guess, it get nil, anyway, i will try again when i am free for several days.

thank you very much for help

**Comment by cyrus-and** [comment] 2021-12-30 17:38
I see, in any case all the fixes boil down to the same couple of things, they can be easily adapted. Honestly in my day to day Emacs usage I only had to fix `imenu-list`, but your mileage may vary, I guess.

Anyway, I'm closing this for now then, feel free to comment/reopen, if you need further assistance.

**Closed by cyrus-and** 2021-12-30 17:38 UTC
