### ISSUE TITLE
Add a predicate for balancing windows?

### ISSUE THREAD

**Issue by zhangpj** [cyrus-and/zoom#3] opened 2017-10-09 17:58 UTC
First I want to thank you for this great package.

However, sometimes the behavior of balancing windows is not ideal. For example, I have `(setq ediff-window-setup-function 'ediff-setup-windows-plain)` in my config, and when I open the ediff window with zoom-mode enabled, the four windows including the bottom control panel will be all balanced. Another example is the calendar window in org mode.

Currently I advise the `zoom--update` function to let it do nothing in certain major modes and buffers. I wonder if you want to add a option for not balancing windows in certain cases.

**Comment by cyrus-and** [comment] 2017-10-09 18:56
Thanks! :)

> However, sometimes the behavior of balancing windows is not ideal.

Yeah, I know but the problem is that you cannot exclude single windows from balancing, it's all or nothing. Assuming to have a predicate that checks, for example, if there is at least an `ediff` buffer displayed and disables the balancing accordingly, the result would be unpleasing as well (more unpleasing IMO) because windows that are shrunk by a previous zoom remain so even when you switch to another window that would possibly allow more space for them. Most importantly, in this situation,  `ediff` buffers would remain small even once selected because they would be among those buffers to ignore.

Moreover, the whole layout is no more stable so the user trying to resize manually a window by dragging the border/mode line would cause glitches, but I guess one could simply unbind that action.

You can play around with this idea by hard coding a condition [here][1], for example:

```el
(unless (inhibit-balance-windows-p)
  (message "BALANCE")
  (balance-windows))
;; check if the selected window is not ignored
(unless (zoom--window-ignored-p)
  (zoom--resize)
  (zoom--fix-scroll))
```

with:

```el
(defun inhibit-balance-windows-p ()
  (member 'calendar-mode
          (mapcar (lambda (window)
                    (with-selected-window window major-mode))
                  (window-list))))
```

and:

```el
(custom-set-variables
 '(zoom-ignored-major-modes '(calendar-mode)))
```

In my experiments results are terrible, but please let me know if you come up with something nice.

[1]: https://github.com/cyrus-and/zoom/blob/52345c2dea4444e41fd6f2ee4733b16cfaa04f91/zoom.el#L169

**Comment by dieggsy** [comment] 2017-10-10 22:29
Related - [which-key](https://github.com/justbur/emacs-which-key) becomes pretty awkward looking with zoom-mode on.

**Comment by cyrus-and** [comment] 2017-10-14 15:52
@dieggsy that can be currently fixed by setting `which-key-popup-type` to `'minibuffer` but it doesn't work well with paging, event without Zoom.

**Comment by cyrus-and** [comment] 2017-10-16 16:37
Some more details about `which-key`.

This mode just like some others, e.g., `imenu-list` uses [*side windows*][1] by default to display contents. Such windows are added as siblings of the root thus they are possibly given a wider share of space by `balance-windows`.

[1]: http://doc.endlessparentheses.com/Fun/display-buffer-in-side-window.html

**Comment by cyrus-and** [comment] 2017-12-30 12:26
So adding a predicate for balancing windows is not feasible (see [this comment][1]). A possible solution would be to preserve the layout when the focus moves to an ignored window, but this is surprisingly hard to implement due to a number of hairy corner cases; I'm not sure if it's worth it to embark upon that. So for the time being this is a won't fix.

[1]: https://github.com/cyrus-and/zoom/issues/3#issuecomment-335254810

**Closed by cyrus-and** 2017-12-30 12:26 UTC
